### ISSUE TITLE
ZIV - GPRS - Exportação

### ISSUE THREAD

**Issue by emanuelsilvapt** [nikito7/han-dev#3]
Bom dia tudo ok?
Antes de mais, e novamente, obrigado pelo excelente traballho no ESPHome!
Coloquei no sábado, finalmente, tudo definitivo; reparei que a partir do momento em que liguei o sistema, a e-redes deixou de receber informação da exportação, pelo menos no site deles.

![image](https://user-images.githubusercontent.com/62140127/158169451-b3b177e3-b67a-47d0-8bcc-bc70c2eb033f.png)

Alguma ideia? Sabe se é comum?
Muito obrigado novamente!

**Comment by nikito7** [comment]
Coincidência ou aumenta o intervalo.

Se tiveres alimentação direta da HAN é imprevisível. 

```yaml
    update_interval: 20s
    address: 0x1
    command_throttle: 500ms
```
